### ISSUE TITLE
Create `$softDelete` shorthand method

### ISSUE THREAD

**Issue by mcastagnetti** [vuex-orm/plugin-soft-delete#2]
This could be helpfull to add `$softDelete` method to entities instances that works the same as other shorthand methods like `$delete` or `$update` to gain in consistency

I know `softDelete` already exists and can be used like below as written in the README : 

```js
// Or you can delete data from an existing model instance.
const user = await User.find(1)
user.softDelete()
```

But this usecase does not seems to work with entities with composite primary keys.

For now, to bypass this limitation I use this workaround, which is clearly not how this plugin is intended to be used : 

```js
this.$update({ ...this, $isDeleted: true })
```

What do you think about this ?

I did not look into how the plugin works so I'll open a PR if I have the time to look at it

**Comment by kiaking** [comment]
@mcastagnetti Oh yes it should! Thank you for pointing out.

PR would be super awesome 🚀 🚀 🚀

**Comment by cuebit** [comment]
This is resolved in an upcoming release.

**Comment by mcastagnetti** [comment]
Awesome, thank you @cuebit !
