### ISSUE TITLE
mark missing from data as deleted

### ISSUE THREAD

**Issue by lzinga** [vuex-orm/plugin-soft-delete#4]
I was wondering if it were possible to instead of directly soft deleting a record by using a command. That you could instead have a method that the data your passing in, if an element is missing from the data in the store it marks it as a soft delete instead of removing it from the store.

Here is an example of what I mean
```js
// Original object
let originalObject = [
    { id: 1, name: "test 1" },
    { id: 2, name: "test 2" }
    { id: 3, name: "test 3" }
    { id: 4, name: "test 4" }
]
originalObject[1].name = "test updated"

// Edit object and remove the first item (with id 1)
let updated = originalObject.splice(0, 1)

// What the local object looks like before any store update
 [
    { id: 2, name: "test updated" }
    { id: 3, name: "test 3" }
    { id: 4, name: "test 4" }
]

VuexOrmTable.insertUpdateOrSoftDelete({ data: updated})

// After vuex orm update what I would expect the object to look like
[
    { id: 1, name: "test 1", $isDeleted: true, deleted_at: ... },
    { id: 2, name: "test updated" }
    { id: 3, name: "test 3" }
    { id: 4, name: "test 4" }
]
```

This way you could potentially pass in a larger object of data with simply missing elements that were removed but when updating the store with it, it instead just marks them as deleted which would still make them hidden considering you need to specifically query to add in the deleted records.

**Comment by lzinga** [comment]
After thinking about this for a while, I feel this may be an anti-pattern of sorts and may not be as useful as I first thought. Will leave this up here in case someone else thinks otherwise.

**Comment by kiaking** [comment]
Ahh, I kinda see your point. But yeah this is quite complicated and maybe bit hard to glance. Interesting thought though! Thanks for your feedback!
